### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ZmeiGorynych** [onepointconsulting/story_teller#1]
Thanks for sharing this! 
What license do you share this under? MIT perhaps, like Langchain and LlamaIndex?
I'd love to reuse some of the code, with attribution of course, but can't without clarity on this.

**Comment by onepointconsulting** [comment]
Hello, many thanks for the inquiry. It is MIT now. Please check: https://github.com/onepointconsulting/story_teller/blob/main/MIT-license.txt. Please go ahead and re-use the code. We are very happy for you to do so.

**Comment by onepointconsulting** [comment]
License added: https://github.com/onepointconsulting/story_teller/blob/main/MIT-license.txt

**Comment by ZmeiGorynych** [comment]
Thanks a lot!
